language: ruby
sudo: false
dist: precise
rvm:
  - 2.1
install: bundle install
script: bundle exec jekyll build

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
