language: ruby
sudo: false
rvm:
  - 2.2
before_install: gem install bundler
install: bundle install
script: npm install --production && bundle exec jekyll build

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
