language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

before_deploy:
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: public
  project_name: jabranr
  name: Jabran Rafique
  email: jabranr@users.noreply.github.com
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: develop
