# Basic info
title: Jabran Rafique
tagline: 'web developer, cartographer'
description: 'I develop ideas that are useful and beneficial to everyone. I am a web developer based in England, UK.'
version: 1.0.2

# Routes
url: http://www.jabran.me
baseurl: /
permalink: /:categories/:title/
avatar: http://www.jabran.me/img/avatar.png

# Pagination
paginate: 10

# Dependencies
markdown: redcarpet
pygments: true

exclude: ['node_modules']