# Site settings
title: Jabran Rafique
email: hello@jabran.me
profession: Consultant full stack web developer
tagline: I like to develop on ideas that are useful and beneficial to everyone.
description: >
  Currently I work at Rated People as Front-end web developer. Outside of my
  professional life I am an Advocate and Regional Lead at Google Map Maker.
  I like to develop on ideas that are useful and beneficial to everyone.

version: 3.0.1
baseurl: ''
url: http://jabran.me
gravatar: 'https://s.gravatar.com/avatar/51253538589838978a4372bfda814c21?s=250'

permalink: /:categories/:title/
paginate_path: '/page/:num/'
paginate: 10

markdown: kramdown
exclude:
  - '.bowerrc'
  - '_site'
  - 'node_modules'
  - 'bower_components'
  - 'README.md'
  - 'vendor'

gems: [jekyll-paginate]
# gems: [jekyll-paginate, github-pages]

compress_html:
  ignore:
    envs: development

# ------------------------------- #
# Configs that can change anytime #
# ------------------------------- #

sass:
  sass_dir: _scss
  style: compressed

facebook:
  username: jabranr
  app_id:   453078498112064

twitter:
  username: jabranr
  app_id:   4503599628147464

github:
  username: jabranr

codepen:
  username: jabranr

google:
  username: JabranRafique
  analytics: UA-9809111-15
  gtm: GTM-MHKHDT
  mapmaker: '?gw=66&uid=208599960765438642668'

hire: false

current_stack:
  - LAMP
  - Symfony2
  - JavaScript
  - jQuery
  - RequireJS
  - Node
  - CSS
  - Sass
  - Gulp
  - Grunt
  - Bower
  - Composer
  - npm
  - Docker
  - AWS

clients:
  - Pathé
  - Arcadia Group
  - London Riviera
  - Thomas Cook
  - OnBlackheath
  - Outfit Fashion
  - ShopStyle
  - Tweepforce
  - Multinet Group
  - Thomas Cook Airlines
  - Brand USA
  - Hobbs
  - Heathrow
  - ThomasCook Cruises
  - Amelia Freer
  - Be More Social
