# Basic info
title: Jabran Rafique
tagline: 'web developer, cartographer'
description: 'I develop ideas that are useful and beneficial to everyone. I am a web developer based in England, UK.'
version: 0.0.2

# Routes
url: http://jabran.me
baseurl: /
permalink: /:categories/:title/
avatar: http://www.gravatar.com/avatar/43b6a42f211e3110d056957f1cd56e2a?s=250
# https://graph.facebook.com/jabranr/picture?size=large

# Pagination
paginate: 10

# Dependencies
markdown: redcarpet
pygments: true
