# Site settings
title: Jabran Rafique
email: hello@jabran.me
profession: Software Engineer (Web)
tagline: I like to develop on ideas that are useful and beneficial to everyone.
description: >
  Currently I work at Rated People as Front-end Web Developer. I have also served as
  an Advocate and Regional Lead at Google Map Maker, and currently a Local Guide on Google Maps.
  I like to develop on ideas that are useful and beneficial to everyone.

version: 3.0.2
baseurl: ""
url: http://jabran.me
gravatar: "https://s.gravatar.com/avatar/51253538589838978a4372bfda814c21?s=250"

permalink: /:categories/:title/
paginate_path: "/page/:num/"
paginate: 10

markdown: kramdown
exclude:
  - "_site"
  - "node_modules"
  - "README.md"

gems: [jekyll-paginate]
# gems: [jekyll-paginate, github-pages]

compress_html:
  ignore:
    envs: development

# ------------------------------- #
# Configs that can change anytime #
# ------------------------------- #

sass:
  sass_dir: _scss
  style: compressed

facebook:
  username: jabranr
  app_id: 453078498112064

twitter:
  username: jabranr
  app_id: 4503599628147464

github:
  username: jabranr

codepen:
  username: jabranr

google:
  username: JabranRafique
  analytics: UA-9809111-15
  gtm: GTM-MHKHDT
  mapmaker: "?gw=66&uid=208599960765438642668"

hire: false

current_stack:
  - LAMP
  - Symfony
  - JavaScript
  - RequireJS
  - NodeJS
  - React
  - Redux
  - CSS
  - Sass
  - Webpack
  - Composer
  - npm
  - docker
  - AWS
  - Atlassian

clients:
  - Pathé
  - Arcadia Group
  - London Riviera
  - Thomas Cook
  - OnBlackheath
  - Outfit Fashion
  - ShopStyle
  - Tweepforce
  - Multinet Group
  - Thomas Cook Airlines
  - Brand USA
  - Hobbs
  - Heathrow
  - ThomasCook Cruises
  - Amelia Freer
  - Be More Social
  - Byte London
