name: CI Checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    uses: jabranr/workflows/.github/workflows/reusable-pr-checks.yml@main
    with:
      run-pre-release: false
      run-unit-test: false
      run-lint: false
      run-typecheck: false

  functional:
    needs: lint-and-build
    uses: jabranr/workflows/.github/workflows/reusable-integration.yml@main
    with:
      test-type: functional

  deployment-status:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Cloudflare Pages deployment
        uses: jabranr/workflows/.github/actions/wait-cf-pages-deployment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge Cloudflare cache
        if: ${{ github.event_name == 'push' }}
        env:
          CF_PURGE_CACHE_TOKEN: ${{ secrets.CF_PURGE_CACHE_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          curl "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $CF_PURGE_CACHE_TOKEN" \
          -d '{"purge_everything": true}'

  e2e-tests:
    if: ${{ github.event_name == 'push' }}
    needs: deployment-status
    uses: jabranr/workflows/.github/workflows/reusable-integration.yml@main
    with:
      test-type: e2e

  performance-audit:
    needs: deployment-status
    runs-on: ubuntu-latest
    steps:
      - name: Get domain
        id: get-domain
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "domain=https://$GITHUB_HEAD_REF.jabranr.pages.dev" >> $GITHUB_OUTPUT
          else
            echo "domain=https://jabran.me" >> $GITHUB_OUTPUT
          fi

      - name: Performance Audit
        uses: jabranr/workflows/.github/actions/performance-audit@main
        with:
          urls: '${{ steps.get-domain.outputs.domain }},${{ steps.get-domain.outputs.domain }}/resume/,${{ steps.get-domain.outputs.domain }}/articles/,${{ steps.get-domain.outputs.domain }}/projects/,${{ steps.get-domain.outputs.domain }}/speaking/'
          github-token: ${{ secrets.GITHUB_TOKEN }}
